# Generated by Django 3.2.6 on 2021-08-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsubmissionmodel',
            name='Appointment_date',
            field=models.DateField(),
        ),
    ]
